# ======================================================================================= #
### STAFF
### LIST POSISI STAFF
GET http://localhost:8080/rumahsakit/staff/posisi
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwOi8va2F3YWhlZHVrYXNpL2lzc3VlciIsInVwbiI6InJlZGhhIiwiZ3JvdXBzIjpbInVzZXIiXSwiZW1haWwiOiJyZWRoYUBlbWFpbC5jb20iLCJpYXQiOjE2NTg3MzY0NjIsImV4cCI6MTY1ODczNzA2MiwianRpIjoiNjU2Mzc3MjYtMWFlMi00MWViLWExYWEtZmQzYTU5MWQyM2ZjIn0.H5nDbb6SJACh2nFPJ9VHPDkafI-C4TNstJ4cqKSvKqMlAafASiGvKaSU2vGA9cj3reY4Xd5WKERzMRsXATKYCAq2ECCQaINE6MbpCgEPV3HwUlWBQwpWKh5PZuG02MzXTI2azC1K2A-DtcJprWSVGnNdY1-cBjf8ikZg2YUByy3MKHKUeI64BRr6X8DGUfqqaoAhrxnp9TWp4g0eAgUMJvtoTTMi_DB9w7oewi7eedomng_Ih3FMAllg9lX-N9ZxA7YqRQFp1ZzuwwRLbxNzB9cSz0ByZt3gTusLRznYRF4e1LrcRfqsG_EDb2F6YF4vFTZYYZOz51EtzXZbdLFFSw

### ADD STAFF
POST http://localhost:8080/rumahsakit/staff
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwOi8va2F3YWhlZHVrYXNpL2lzc3VlciIsInVwbiI6ImFsZmF0aCIsImdyb3VwcyI6WyJ1c2VyIl0sImVtYWlsIjoicmVkaGFAZW1haWwuY29tIiwiaWF0IjoxNjU4NzQwNjQ5LCJleHAiOjE2NTg3NDEyNDksImp0aSI6IjViNzRiOWY5LTlkNTgtNGI2MS04MWUzLTMxYmY2ZGRlYTcyZSJ9.f73S_MGDSN-OGM92cHu4Cd0MTRku8q0KklJFQRv5eUiNm1Za6FPWrkKUOdYUS-xNSrkMyLoCJEDni42IV8ng_02mY5j0IQgd1cNP82QpH3O8DsTtmx0TboEMms_qq0uSb_5HYApZszjSXASWaUG3fHBYTvglV3RAUuNT7KOfXdFZF6iLmI0pc39QfMJEHgsYvt4uHUsRM0GPr7_4IBd_YqvYlznetrZzXcgT2Yz-kIXrtHhMYBC7fhBbrk1X-r0xI_sqBngtr5PmHI4mvYBg32hD98L53HE0QExJ5apafRYKI1WsL7y0R6TGtZI-FtkPK2Mm0OUhT_NpRahmrkp2dg
Content-Type: application/json

{
  "nama_lengkap":"Cahyo",
  "gender":"pria",
  "posisi":"Security",
  "gaji":20000000,
  "email":"cahyo@gmail.com",
  "phone_number":"085325224842",
  "status":"staff active"
}

### GET STAFF
// pagination 5 list data with filter by nama, email, phoneNumber
// can get data with page number from pagination by page
GET http://localhost:8080/rumahsakit/staff
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwOi8va2F3YWhlZHVrYXNpL2lzc3VlciIsInVwbiI6InJlZGhhIiwiZ3JvdXBzIjpbInVzZXIiXSwiZW1haWwiOiJyZWRoYUBlbWFpbC5jb20iLCJpYXQiOjE2NTg3Mzg5MzUsImV4cCI6MTY1ODczOTUzNSwianRpIjoiM2ZkN2ExZGItMjdjNy00N2EwLWFlMzctMTlhYmZhYTU5NDhkIn0.UMogOZgVXOREWONDcK1SfPB-Zmo5rWOTY9gLGaxtGzuTSDTWsWjLkZUt4hyu71HWfXlTF7tJLIjI6X3jtv69kTEjw1iNQcL_6owGihjTB4gFjnGxHuOqYe_0r-Z_cC0-Ay-DlvmlNrxEc6U21TvJuk9TKoN4vMn_AbsBmxzj2O7egfDH901_a0H9OerIAf4UdTFUTaMkTjGFD8nNJkqQwTvnqsx1G8SJsgwXE3dmdSEyNNx1BdYuKqlWZ_pmyzdxxzye2BGjLYaIasxKuj_hKOvU0FdBrtr-_nN_6FC4Kqbx2-4y7_0-SAKJ8q25A6XYjwwT6zZal6W48-eBgPayqA

### DELETE STAFF By Id
DELETE http://localhost:8080/rumahsakit/staff/3
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwOi8va2F3YWhlZHVrYXNpL2lzc3VlciIsInVwbiI6InJlZGhhIiwiZ3JvdXBzIjpbInVzZXIiXSwiZW1haWwiOiJyZWRoYUBlbWFpbC5jb20iLCJpYXQiOjE2NTg3MzY0NjIsImV4cCI6MTY1ODczNzA2MiwianRpIjoiNjU2Mzc3MjYtMWFlMi00MWViLWExYWEtZmQzYTU5MWQyM2ZjIn0.H5nDbb6SJACh2nFPJ9VHPDkafI-C4TNstJ4cqKSvKqMlAafASiGvKaSU2vGA9cj3reY4Xd5WKERzMRsXATKYCAq2ECCQaINE6MbpCgEPV3HwUlWBQwpWKh5PZuG02MzXTI2azC1K2A-DtcJprWSVGnNdY1-cBjf8ikZg2YUByy3MKHKUeI64BRr6X8DGUfqqaoAhrxnp9TWp4g0eAgUMJvtoTTMi_DB9w7oewi7eedomng_Ih3FMAllg9lX-N9ZxA7YqRQFp1ZzuwwRLbxNzB9cSz0ByZt3gTusLRznYRF4e1LrcRfqsG_EDb2F6YF4vFTZYYZOz51EtzXZbdLFFSw

### UPDASTE GAJI STAFF By Id
PUT http://localhost:8080/rumahsakit/staff/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwOi8va2F3YWhlZHVrYXNpL2lzc3VlciIsInVwbiI6InJlZGhhIiwiZ3JvdXBzIjpbInVzZXIiXSwiZW1haWwiOiJyZWRoYUBlbWFpbC5jb20iLCJpYXQiOjE2NTg3MzY0NjIsImV4cCI6MTY1ODczNzA2MiwianRpIjoiNjU2Mzc3MjYtMWFlMi00MWViLWExYWEtZmQzYTU5MWQyM2ZjIn0.H5nDbb6SJACh2nFPJ9VHPDkafI-C4TNstJ4cqKSvKqMlAafASiGvKaSU2vGA9cj3reY4Xd5WKERzMRsXATKYCAq2ECCQaINE6MbpCgEPV3HwUlWBQwpWKh5PZuG02MzXTI2azC1K2A-DtcJprWSVGnNdY1-cBjf8ikZg2YUByy3MKHKUeI64BRr6X8DGUfqqaoAhrxnp9TWp4g0eAgUMJvtoTTMi_DB9w7oewi7eedomng_Ih3FMAllg9lX-N9ZxA7YqRQFp1ZzuwwRLbxNzB9cSz0ByZt3gTusLRznYRF4e1LrcRfqsG_EDb2F6YF4vFTZYYZOz51EtzXZbdLFFSw
Content-Type: application/json

{
  "gaji":15000000
}
