# ======================================================================================= #
### USER
### REGISTRATION
POST http://localhost:8080/rumahsakit/user/register
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwOi8va2F3YWhlZHVrYXNpL2lzc3VlciIsInVwbiI6InN1cGVyQWRtaW4iLCJncm91cHMiOlsic3VwZXJBZG1pbiJdLCJlbWFpbCI6InJlZGhhQGVtYWlsLmNvbSIsImlhdCI6MTY1ODc0MDYyMCwiZXhwIjoxNjU4NzQxMjIwLCJqdGkiOiI1MWZkMDRlMi1iZjU5LTRmMzEtODM3Yi03MjM3OGUyZWIwZmYifQ.AySkjlMi2eEFOaANantZzsNn43-TmhGUMe3-s6X_gParRSpmQ6RCIcD2ZSjgQmW_YXFbDA8o9wfsCrQokv3s9TnCI2ZQ-S-SjlZ2oE1yjwV8_z_7AldDmIa1xSR0b8c8F_QGXakDWT5AUsU3mDbgrEDl8az952Rg6rJxeLHLL8U246ioHl3OXCCkE7QvV6U-KM0q1XAJY_fB4F4G0nV6HrhImPpO-c-SLgOuvADxvO0qPfgpU1zo8xezQ9SmXx4RUSBaJgWzJC8lyPI8dy8mwOtEDjMNDxwgZjz2nBbrhtXWcNQQ-xTPzxc9EFcz1puSTTRsWxPGAqf-iSsyOSfW-Q
Content-Type: application/json

{
  "name":"alfath",
  "username":"alfath",
  "password":"alfath",
  "email":"alfath@gmail.com",
  "phoneNumber":"085325224829",
  "userType":"user",
  "permissions":[
    "user"
  ]
}

### LOGIN
POST http://localhost:8080/rumahsakit/user/login
Content-Type: application/json

{

  "username":"alfath",
  "password":"alfath"
}
